### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by brucou** [miracle2k/react-arrow#5]
Good job there!

However I could not figure out how the orign and target of the arrows were determined. Is that with respect to the bounding box of the enclosing div?

**Comment by miracle2k** [comment]
I'm not sure I understand exactly what you mean. The arrow does not really point from or to something, not that it knows  at least.

The length really means the size of the line vs the size of the arrow head. So you'll get an SVG with a bounding box, and an arrow inside at a certain angle.

**Comment by brucou** [comment]
Alright I think I understand. From the demo, I thought the arrow was pointing at a specific place. But actually positioning is left to the user. Fair enough. Thanks
